import constants from './constants'

const {
  lightBackgroundDefault,
  lightBrandSecondary,
  lightBackgroundMedium,
  lightBackgroundStrong,
  lightBackgroundHighlightDisabled,
  lightTextDefault,
  lightTextWeak,
  lightTextDisabled,
  lightBorderDefault,
  lightBrandDefault,
  lightBoxShadow,
  lightPaperBoxShadow,
  lightErrorMain,
  lightDanger,
  lightGoogleButtonBackground,
  lightGoogleButtonText,
  lightSuccess,
  lightSuccessWeak,
  lightSuccessStrong,
  lightSelected,
  lightDangerWeak,
  lightDangerStrong,
  lightDisabledButtonBackground,
  lightWarningWeak,
  lightWarningDefault,
  darkBackgroundDefault,
  darkBrandSecondary,
  darkBackgroundMedium,
  darkBackgroundStrong,
  darkBackgroundHighlightDisabled,
  darkTextDefault,
  darkTextWeak,
  darkTextDisabled,
  darkBorderDefault,
  darkBrandDefault,
  darkBoxShadow,
  darkErrorMain,
  darkDanger,
  darkGoogleButtonBackground,
  darkGoogleButtonText,
  darkSuccess,
  darkSuccessWeak,
  darkSuccessStrong,
  darkSelected,
  darkDangerWeak,
  darkDangerStrong,
  darkDisabledButtonBackground,
  darkWarningWeak,
  darkWarningDefault,
  ...rest
} = constants

export const lightTheme = {
  name: 'lightTheme',
  backgroundDefault: lightBackgroundDefault,
  backgroundMedium: lightBackgroundMedium,
  backgroundStrong: lightBackgroundStrong,
  backgroundHighlightDisabled: lightBackgroundHighlightDisabled,
  textDefault: lightTextDefault,
  textWeak: lightTextWeak,
  textDisabled: lightTextDisabled,
  borderDefault: lightBorderDefault,
  brandDefault: lightBrandDefault,
  brandSecondary: lightBrandSecondary,
  boxShadow: lightBoxShadow,
  paperBoxShadow: lightPaperBoxShadow,
  errorMain: lightErrorMain,
  danger: lightDanger,
  googleButtonBackground: lightGoogleButtonBackground,
  googleButtonText: lightGoogleButtonText,
  success: lightSuccess,
  successWeak: lightSuccessWeak,
  successStrong: lightSuccessStrong,
  selected: lightSelected,
  dangerWeak: lightDangerWeak,
  dangerStrong: lightDangerStrong,
  disabledButtonBackground: lightDisabledButtonBackground,
  warningWeak: lightWarningWeak,
  warningDefault: lightWarningDefault,
  ...rest,
}

export const darkTheme = {
  name: 'darkTheme',
  backgroundDefault: darkBackgroundDefault,
  backgroundMedium: darkBackgroundMedium,
  backgroundStrong: darkBackgroundStrong,
  backgroundHighlightDisabled: darkBackgroundHighlightDisabled,
  textDefault: darkTextDefault,
  textWeak: darkTextWeak,
  textDisabled: darkTextDisabled,
  borderDefault: darkBorderDefault,
  brandDefault: darkBrandDefault,
  brandSecondary: darkBrandSecondary,
  boxShadow: darkBoxShadow,
  paperBoxShadow: darkBoxShadow,
  errorMain: darkErrorMain,
  danger: darkDanger,
  googleButtonBackground: darkGoogleButtonBackground,
  googleButtonText: darkGoogleButtonText,
  success: darkSuccess,
  successWeak: darkSuccessWeak,
  successStrong: darkSuccessStrong,
  selected: darkSelected,
  dangerWeak: darkDangerWeak,
  dangerStrong: darkDangerStrong,
  disabledButtonBackground: darkDisabledButtonBackground,
  warningWeak: darkWarningWeak,
  warningDefault: darkWarningDefault,
  ...rest,
}
